# SAGE Protocol Configuration

# General Settings
similarity_threshold: 0.9
max_retries: 3
default_model: "gemma3:4b"

evaluator_model: "deepseek-r1:1.5b"  # Model used for LLM-based evaluation

# Available Models (Ollama local only)
available_models:
  - "gemma3:4b"
  - "deepseek-r1:1.5b"
  - "qwen3:1.7b"

# Model Assignments by Task Type
model_assignments:
  creative: "gemma3:4b"
  technical: "deepseek-r1:1.5b"
  summarization: "gemma3:4b"
  analysis: "deepseek-r1:1.5b"
  code: "deepseek-r1:1.5b"
  other: "gemma3:4b"
  evaluation: "deepseek-r1:1.5b"  # Default evaluator model

# Model Parameters
model_parameters:
  gemma3:4b:
    temperature: 0.7
    max_tokens: 2000
  deepseek-r1:1.5b:
    temperature: 0.7
    max_tokens: 2000
  qwen3:1.7b:
    temperature: 0.7
    max_tokens: 2000

# Retry Strategy
retry_strategy:
  max_attempts: 3
  backoff_factor: 2
  initial_delay: 1

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 