# SAGE Protocol Configuration

# General Settings
similarity_threshold: 0.9
max_retries: 3
default_model: "gemma3:4b"

evaluator_model: "deepseek-r1:1.5b"  # Model used for LLM-based evaluation

# Available Models (Ollama local only)
available_models:
  - "gemma3:4b"
  - "deepseek-r1:1.5b"
  - "qwen3:1.7b"
  - "models/gemini-2.5-flash-preview-05-20"  # Gemini (cloud)

# Model Assignments by Task Type
model_assignments:
  creative: "gemma3:4b"
  technical: "deepseek-r1:1.5b"
  summarization: "gemma3:4b"
  analysis: "deepseek-r1:1.5b"
  code: "deepseek-r1:1.5b"
  other: "gemma3:4b"

# Model Parameters
model_parameters:
  gemma3:4b:
    temperature: 0.7
    max_tokens: 2000
  deepseek-r1:1.5b:
    temperature: 0.7
    max_tokens: 2000
  qwen3:1.7b:
    temperature: 0.7
    max_tokens: 2000
  models/gemini-2.5-flash-preview-05-20:
    temperature: 0.7
    max_tokens: 4096

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Model Provider Map
model_provider_map:
  gemma3:4b: local
  deepseek-r1:1.5b: local
  qwen3:1.7b: local
  models/gemini-2.5-flash-preview-05-20: cloud 